apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis

spec:
  # tells k8s which pods to manage(redis)
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      # tells k8s what label to use for the pods it manages
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
