apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  selector:
    matchLabels:
      app: url-shortener
  replicas: 3 # Start with 3 replicas
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: aniruddh0/url-shortener:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: url-shortener-config
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener
spec:
  type: NodePort
  selector:
    app: url-shortener
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
